import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/custom/Navbar";
import Sidebar from "@/components/custom/Sidebar";
import { ThemeProvider } from "next-themes";
import ReduxProvider from "@/lib/redux-provider";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${rubik.variable} h-full`}
      suppressHydrationWarning
    >
      <body
        className={` antialiased h-full`}
        style={{ fontFamily: "var(--font-rubik), sans-serif" }}
      >
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
          >
            {/* Full height flex layout */}
            <div className="flex h-screen overflow-hidden">
              {/* Fixed sidebar */}
              <aside className="w-20 fixed top-0 left-0 h-screen z-40">
                <Sidebar />
              </aside>

              {/* Main content area with left padding for sidebar */}
              <div className="flex-1 flex flex-col pl-20">
                {/* Sticky navbar */}
                <Navbar />
                {/* Scrollable content */}
                <main className="flex-1">{children}</main>
              </div>
            </div>

            <Toaster richColors />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
