import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/custom/Navbar";
import Sidebar from "@/components/custom/Sidebar";
import { ThemeProvider } from "next-themes";
import ReduxProvider from "@/lib/redux-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <ReduxProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {/* Full height flex layout */}
            <div className="flex h-screen overflow-hidden">
              {/* Fixed sidebar */}
              <aside className="w-20 fixed top-0 left-0 h-screen z-40">
                <Sidebar />
              </aside>

              {/* Main content area with left padding for sidebar */}
              <div className="flex-1 flex flex-col pl-20">
                {/* Sticky navbar */}
                <Navbar />
                {/* Scrollable content */}
                <main className="flex-1">{children}</main>
              </div>
            </div>

            <Toaster richColors />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
