export const metrics = [
  { label: "Working Hours", value: "36 H : 10 M : 20 S" },
  { label: "Actual Working Time", value: "32 H : 00 M : 00 S", info: true },
  { label: "Tracked Hours", value: "00 H : 00 M : 00 S" },
  { label: "Time Difference", value: "36 H : 10 M : 20 S", info: true },
  { label: "Clock In Days", value: 5, color: "text-green-600" },
  { label: "Payroll Present Days", value: 7 },
  { label: "OD/Remote work", value: 0, color: "text-green-600" },
  { label: "Absent", value: 0, color: "text-red-500" },
  { label: "Shift Not Start", value: 0, color: "text-red-500" },
  { label: "On Leave", value: 0 },
  { label: "Late IN", value: 0, color: "text-yellow-500" },
  { label: "Early OUT", value: 0, color: "text-yellow-500" },
  { label: "Paid Leave", value: 0 },
  { label: "Unpaid Leave", value: 0, color: "text-red-500" },
  { label: "OD/Hourly Remote work", value: "00H : 00M" },
  { label: "Hourly Paid Leave", value: "00H : 00M" },
  { label: "Hourly Unpaid Leave", value: "00H : 00M" },
  { label: "Weekend", value: 2 },
  { label: "Holiday", value: 0 },
];

export const RemoteData = [
  {
    id: "DVIJ19",
    name: "Jatin Ramani",
    image:
      "https://office.dvijinfotech.com/uploads/staff_profile_images/67/small_WhatsApp%20Image%202024-09-02%20at%2021.15.52_0a414dd2.jpg",
    type: "Work From Home",
    country: "India",
    state: "Gujarat",
    from: "Mon 05 May, 2025",
    to: "Tue 06 May, 2025",
    nuOfDaysHours: "2",
    status: "approved",
    requestedOn: "02/05/2025 11:29 AM",
    reason: "I need to visit my village on Tomorrow ...More",
    actionBy: "Karshan",
  },
  {
    id: "DVIJ20",
    name: "Sneha Patel",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    type: "Remote Work",
    country: "India",
    state: "Maharashtra",
    from: "Wed 07 May, 2025",
    to: "Wed 07 May, 2025",
    nuOfDaysHours: "1",
    status: "pending",
    requestedOn: "05/05/2025 10:00 AM",
    reason: "Home internet setup work ...More",
    actionBy: "-",
  },
  {
    id: "DVIJ21",
    name: "Aman Mehta",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    type: "Work From Home",
    country: "India",
    state: "Delhi",
    from: "Fri 09 May, 2025",
    to: "Fri 09 May, 2025",
    nuOfDaysHours: "1",
    status: "rejected",
    requestedOn: "06/05/2025 02:15 PM",
    reason: "Family medical emergency ...More",
    actionBy: "Karshan",
  },
  {
    id: "DVIJ22",
    name: "Riya Shah",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    type: "Remote Work",
    country: "India",
    state: "Rajasthan",
    from: "Mon 12 May, 2025",
    to: "Tue 13 May, 2025",
    nuOfDaysHours: "2",
    status: "approved",
    requestedOn: "10/05/2025 09:45 AM",
    reason: "Staying with family in hometown ...More",
    actionBy: "Karshan",
  },
  {
    id: "DVIJ23",
    name: "Harsh Vora",
    image: "https://randomuser.me/api/portraits/men/85.jpg",
    type: "Work From Home",
    country: "India",
    state: "Karnataka",
    from: "Wed 14 May, 2025",
    to: "Wed 14 May, 2025",
    nuOfDaysHours: "1",
    status: "pending",
    requestedOn: "13/05/2025 05:30 PM",
    reason: "Laptop issue - technician visit scheduled ...More",
    actionBy: "-",
  },
];

export const lateInData = [
  {
    date: "Thu 05 Jun, 2025",
    clockInTime: "10:23 AM",
    lateInTime: "00 H : 03 M : 21 S",
    penalty: "-",
    lateInReason: "Traffic Issue",
  },
  {
    date: "Fri 06 Jun, 2025",
    clockInTime: "10:40 AM",
    lateInTime: "00 H : 15 M : 00 S",
    penalty: "₹100",
    lateInReason: "Internet issues at home",
  },
];
export const earlyOutData = [
  {
    date: "Thu 05 Jun, 2025",
    earlyOutTime: "5:23 PM",
    clockOutStatus: "remain",
    reason: "Need to change my room",
    actionBy: "Karshan",
  },
];
